# Generated by Django 3.0.1 on 2019-12-28 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_catagoryies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagoryies',
            old_name='name',
            new_name='person',
        ),
    ]
